name: Crawl new data
on:
  schedule:
    - cron: '30 23 * * 0' # Run on 12:30AM every sundays

jobs:
  crawl:
    name: Crawl data and save data
    runs-on: ubuntu-latest
    steps:
    - name: Crawl and save data
      run: curl 'https://macbook-finder-server.onrender.com/crawl'
